# Generated by Django 5.0.2 on 2024-02-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='slug',
            field=models.SlugField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
