# Generated by Django 5.0.2 on 2024-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards_app", "0002_flashcard_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
