# Generated by Django 4.2 on 2024-05-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='factor',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='noise',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
