# Generated by Django 4.2 on 2024-01-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatsFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_owner', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=1000)),
                ('source', models.CharField(max_length=255)),
                ('createdAt', models.CharField(max_length=255)),
                ('updatedAt', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('deleted', models.BooleanField()),
                ('used', models.BooleanField()),
            ],
        ),
    ]
